### ISSUE TITLE
tsh role request hangs / EOF quickly

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#29] opened 2020-01-21 23:21 UTC
While requesting a role, after  5- 10min I had an EOF error.   

```
➜  ~ tsh login --request-roles=admin
Seeking request approval... (id: e1be5fa8-b816-4fd4-a6ce-833fa2497db7)
error: EOF
```

**Comment by xnutsive** [comment] 2020-01-22 01:36
I assume the expected behavior is that the command should wait until the request is granted or declined and output the result?

**Comment by benarent** [comment] 2020-01-23 00:52
There are likely two types of approval, real-time or batched. I would expect many to be batched and delayed. 

Instead of EOF: I would suggest we supply the CLI instructions for how to check tctl status. 

```
➜  ~ tsh login --request-roles=admin
Seeking request approval... (id: e1be5fa8-b816-4fd4-a6ce-833fa2497db7)
Still waiting for approval check status with `tctl request ls`
```

**Comment by xnutsive** [comment] 2020-01-23 02:02
So people running tsh client would usually also have access to a subset of tctl features, limited by their roles, and will in most cases have access to `tctl request ls`?

**Comment by benarent** [comment] 2020-01-23 22:37
ow, that's my bad. I think this will have to be a new feature for tsh.

**Comment by benarent** [comment] 2020-01-23 22:37
@fspmarshall Is is possible to check the status of a role request for a user using `tsh`?

**Comment by xnutsive** [comment] 2020-02-01 03:10
In the meantime, I've logged in with `tsh` and tested that `tsh login --request-roles` works if the request is denied / approved. 

Testing what happens if I don't approve/deny it quickly now, I'll update the comment ;)

**Comment by xnutsive** [comment] 2020-03-05 02:53
Since this hasn't happened in any of our testing recently, I'll close the issue in this repo. I think it makes sense to provide a way for `tsh` to inquire about a request / role status though. I can create and document an issue in Teleport if you'd like me to — please let me know @fspmarshall, @benarent.

**Closed by xnutsive** 2020-03-05 02:53 UTC
