### ISSUE TITLE
 V4 role in Terraform Provider

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport-plugins#286] opened 2021-08-16 14:15 UTC
If a V4 role is set in a Terraform configuration it always recognizes it as a change from V3 after application.

```
resource "teleport_role" "server_user" {
  metadata {
    name        = "server-user"
    description = "Server access user role"
  }

  version = "v4"

  spec {
    options {
      max_session_ttl = "12h"
      port_forwarding = true
    }

    allow {
      logins = ["ubuntu", "ec2-user"]

      node_labels {
        # For now, allow any labels
        key = "*"
        value = ["*"]
      }

    }
  }
}
```

Change

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # teleport_role.server_user will be updated in-place
  ~ resource "teleport_role" "server_user" {
        id      = "server-user"
      ~ version = "v3" -> "v4"
        # (1 unchanged attribute hidden)
```

**Comment by gzigzigzeo** [comment] 2021-08-16 16:48
Could you please tell me, which Teleport version are you using (or Teleport Cloud, possibly)? From my perspective it looks like Terraform sends the new version to the Teleport instance, but Teleport ignores it and provides V3 back to Terraform after update, so I need to know the exact Teleport version to reproduce and/or provide a workaround.

**Comment by stevenGravy** [comment] 2021-08-16 16:55
6.2.7 on-prem @gzigzigzeo

**Comment by stevenGravy** [comment] 2021-08-16 17:55
this is also happening in the latest 7.0.2 release

**Comment by gzigzigzeo** [comment] 2021-08-17 17:21
@stevenGravy I have PR fixing this, it is supposed to be merged in the next provider release.

**Comment by gzigzigzeo** [comment] 2021-08-19 11:59
https://github.com/gravitational/teleport-plugins/pull/263

**Closed** 2022-08-06 13:02 UTC
Labels: P0, terraform provider
