### ISSUE TITLE
Terraform provider reports resource failed to create even when it was created successfully

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport-plugins#540] opened 2022-05-04 18:37 UTC
Given the following resource:

```yaml
resource "teleport_app" "app" {
  metadata = {
    name        = "example"
    description = "simple example"
    labels = {
      "teleport.dev/origin" = "dynamic"
      "test" = "true"
    }
  }

  spec = {
    insecure_skip_verify = true
    uri         = "http://example.com"
  }
}
```

This type of error can happen:

```
│ Error: Error reading App
│
│   with teleport_app.app,
│   on main.tf line 84, in resource "teleport_app" "app":
│   84: resource "teleport_app" "app" {
│
│ Terraform user has no rights to perform this action. Check that Terraform user role has ['list','create','read','update','delete'] verbs for 'app' resource.
│ 	application "example" doesn't exist
╵
```

After this error, the app/example object definitely exists in the teleport backend.

I believe this section of the code is what throws the error: https://github.com/gravitational/teleport-plugins/blob/master/terraform/provider/resource_teleport_app.go#L104-L109

After eliminating the teleport rbac system and any user/role issues out, I figured there must be a race condition happening. The original environment where this was reported is using a dynamodb backend, which can have a very small window after a write before subsequent reads are successful.

I was able to force this to happen reliably in a lab. I set up a teleport cluster with a single replica etcd, and multiple teleport auth+proxy replicas. I then degraded the performance of etcd by running `tc qdisc add dev eth0 root netem delay 4000ms` inside the container where etcd is running, which adds four seconds of latency. The cluster still works, but every operation to etcd takes much longer. Once I did this, I was able to reliably reproduce the error above.

I tried to get a similar error from creating a role or user, but wasn't able to. I did, however, get a similar error when I marked a teleport_role resource as tainted and reran terraform. The delete succeeded, but the subsequent create failed because the `Client.GetRole` call returned the resource that had just been deleted.

```
╷
│ Error: Role exists in Teleport
│
│   with teleport_role.terraform-test,
│   on main.tf line 20, in resource "teleport_role" "terraform-test":
│   20: resource "teleport_role" "terraform-test" {
│
│ Role exists in Teleport. Either remove it (tctl rm role/terraform-test) or import it to the existing state (terraform import teleport_app.terraform-test terraform-test)
╵
```

I figure the terraform provider should have some retries built in to help the backend settle, especially since teleport can use backends that are eventually consistent. A very simple retry+exponential backoff on the step that tries to get the newly created resource could help ensure that new resource is properly settled. A similar get attempt may be appropriate after the resource delete is called to help a case where terraform is replacing a resource.

gz#5009

**Comment by marcoandredinis** [comment] 2022-05-05 08:03
Can you please do the same test but disabling cache on the Teleport side?
```yaml
teleport:
  cache:
    enabled: false
```

I suspect this is a duplicate of https://github.com/gravitational/teleport-plugins/issues/513

**Comment by programmerq** [comment] 2022-05-09 15:23
After disabling the cache on the teleport pods, the etcd latency seems to completely break the cluster-- presumably because the pods all need to do many more calls to the backend and some critical calls have timeouts that are too low.

I agree that this is likely a duplicate of #513 and a pause, delay, or simple retry may be all that is needed on the final Client.GetApp call that is done after the Client.CreateApp call.

This can be closed in favor of #513.

**Comment by marcoandredinis** [comment] 2022-05-12 09:06
Just created a PR to add retries when creating resources (thank you for the suggestion)
It should fix the issue 🤞

**Closed** 2022-05-18 09:25 UTC
Labels: bug, terraform provider, c-kl

**Comment by bryanhorstmann** [comment] 2024-02-14 13:59
I'm facing this issue when creating a bot user using the Terraform provider. I'm using provider 15.0.1 and cluster 15.0.1

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # teleport_bot.teleport_machine_id will be created
  + resource "teleport_bot" "teleport_machine_id" {
      + id        = (known after apply)
      + name      = "teleport-machine-id"
      + role_name = (known after apply)
      + roles     = [
          + "teleport-machine-id",
        ]
      + token_id  = (sensitive value)
      + token_ttl = (known after apply)
      + user_name = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```
╷
│ Error: Error creating Bot
│ 
│   with teleport_bot.teleport_machine_id,
│   on teleport_machine_id.tf line 48, in resource "teleport_bot" "teleport_machine_id":
│   48: resource "teleport_bot" "teleport_machine_id" {
│ 
│ Terraform user has no rights to perform this action. Check that Terraform
│ user role has ['list','create','read','update','delete'] verbs for 'bot'
│ resource.
│       token with name "1707918339097787155" not found, create the token or do
│ not set TokenName: provisioning token(**************87155) not found
╵
```

But I can see all the resources:
```
→ tctl bots ls
Bot                 User                    Roles                   
------------------- ----------------------- ----------------------- 
teleport-machine-id bot-teleport-machine-id bot-teleport-machine-id 

→ tctl users ls                       
User                                Roles                                                          
----------------------------------- --------------------------------------------------------------                                                 
bot-teleport-machine-id             bot-teleport-machine-id   

→ tctl get role/bot-teleport-machine-id   
kind: role
metadata:
  description: Automatically generated role for bot teleport-machine-id
  id: 1707918628738466431
  labels:
    teleport.internal/bot: teleport-machine-id
  name: bot-teleport-machine-id
  revision: 65a90139-ff78-4200-9bd2-96f708f208ae
```

**Comment by bryanhorstmann** [comment] 2024-02-14 14:09
Apologies, ignore this. The error was in-front of me.

In the terraform provider, when creating a bot, it has a field called `token_id`. This is in fact, not the id, but the name of the token. 😮‍💨 

This works...
```
resource "teleport_bot" "teleport_machine_id" {
  name     = local.teleport_machine_id_name
  token_id = teleport_provision_token.teleport_machine_id.metadata.name
  roles    = [teleport_role.teleport_machine_id.id]
}
```
