### ISSUE TITLE
[event forwarder] configure command outputs non-working setup

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport-plugins#747] opened 2023-01-25 22:41 UTC
When using the `teleport-event-handler configure` command, it generates a self-signed ca and signs a server cert and a client cert. All three certs have _identical_ subject names. This seems to work on some TLS implementations and not others.

The error that happens is the plugin will start up, but as soon as it tries to connect to the fluentd endpoint, it will throw errors related to the cert: `ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118`

<details>
<summary>Click to expand full log output</summary>

```
./teleport-event-handler start --config teleport-event-handler.toml
INFO   Using batch size batch:20 event-handler/cli.go:236
INFO   Using namespace namespace:default event-handler/cli.go:237
INFO   Using type filter types:[] event-handler/cli.go:238
INFO   Skipping session events of type types:map[print:{}] event-handler/cli.go:239
INFO   Using start time value:<nil> event-handler/cli.go:240
INFO   Using timeout timeout:10s event-handler/cli.go:241
INFO   Using Fluentd url url:https://localhost:8888/test.log event-handler/cli.go:242
INFO   Using Fluentd session url url:https://localhost:8888/session event-handler/cli.go:243
INFO   Using Fluentd ca ca:/opt/event-handler/ca.crt event-handler/cli.go:244
INFO   Using Fluentd cert cert:/opt/event-handler/client.crt event-handler/cli.go:245
INFO   Using Fluentd key key:/opt/event-handler/client.key event-handler/cli.go:246
INFO   Using Teleport identity file file:/opt/event-handler/identity event-handler/cli.go:249
INFO   Created storage directory dir:storage/teleport.example.com_443 event-handler/state.go:112
WARN   open : no such file or directory event-handler/teleport_events_watcher.go:85
INFO   At least one non-expired credential has been found, continuing startup event-handler/teleport_events_watcher.go:91
INFO   Using initial cursor value cursor: event-handler/app.go:191
INFO   Using initial ID value id: event-handler/app.go:192
INFO   Using start time from state value:2023-01-25 21:56:06 +0000 UTC event-handler/app.go:193
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
^CINFO   Attempting graceful shutdown... lib/signals.go:46
ERRO   Watcher event loop failed error:[
ERROR REPORT:
Original Error: *url.Error Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority
Stack Trace:
	/go/src/github.com/gravitational/teleport-plugins/event-handler/fluentd_client.go:108 main.(*FluentdClient).Send
	/go/src/github.com/gravitational/teleport-plugins/event-handler/app.go:113 main.(*App).SendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:149 main.(*EventsJob).sendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:118 main.(*EventsJob).handleEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:104 main.(*EventsJob).runPolling
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:65 main.(*EventsJob).run
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:230 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:251 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:97 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority] event-handler/events_job.go:81
ERRO   Terminating with fatal error [1]... error:[
ERROR REPORT:
Original Error: *url.Error Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority
Stack Trace:
	/go/src/github.com/gravitational/teleport-plugins/event-handler/fluentd_client.go:108 main.(*FluentdClient).Send
	/go/src/github.com/gravitational/teleport-plugins/event-handler/app.go:113 main.(*App).SendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:149 main.(*EventsJob).sendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:118 main.(*EventsJob).handleEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:104 main.(*EventsJob).runPolling
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:65 main.(*EventsJob).run
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:230 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:251 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:97 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority] lib/bail.go:28
```

</details>

<details>
<summary>teleport-event-handler.toml</summary>

```toml
storage = "./storage"
timeout = "10s"
batch = 20
namespace = "default"

[forward.fluentd]
ca = "/opt/event-handler/ca.crt"
cert = "/opt/event-handler/client.crt"
key = "/opt/event-handler/client.key"
url = "https://localhost:8888/test.log"
session-url = "https://localhost:8888/session"

[teleport]
addr = "teleport.example.com:443"
identity = "identity"
```

</details>

```
for i in ca.crt client.crt server.crt; do openssl x509 -noout -subject -serial -in ${i}; done
subject=C = US, CN = localhost
serial=ACFC656D7263BCFABA7C19AA86D04F78
subject=C = US, CN = localhost
serial=881D414631868529C964946D5A315B73
subject=C = US, CN = localhost
serial=26DFB5FA3C9A598F7AD7DB59EC26DF5B
```

If the subject was different for each cert, this would avoid the problem altogether.

### Workarounds

Generate your own CA, client, and server certificates instead of using the generated certs.

### Steps to Reproduce

Follow the guide found here: https://goteleport.com/docs/management/export-audit-events/fluentd/?scope=enterprise

The error happens on a fresh ubuntu 22.04 environment, which has `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)` installed on it.

The same steps on my mac that has `LibreSSL 3.3.6`, plus all the apple trust store extensions for its openssl and tls libraries does not reproduce the problem.

**Comment by programmerq** [comment] 2023-02-03 19:53
## Workaround 1

Use a single self-signed cert for the client, ca, and server in both fluent.conf and teleport-event-handler.toml:

```
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout selfsigned.key -out selfsigned.crt -subj '/C=US/CN=localhost' -addext 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:0:0:0:0:0:0:0:1' -addext 'extendedKeyUsage=serverAuth,clientAuth'
```

fluent.conf snippet:
 
```
    <transport tls>
        client_cert_auth true
        ca_path "/keys/selfsigned.crt"
        cert_path "/keys/selfsigned.crt"
        private_key_path "/keys/selfsigned.key"
        private_key_passphrase "2877959b4c5454418242feb03c892005b9abe7a0070db396e40d20f7f6fbb3d0"
    </transport>
```

teleport-event-handler.toml snippet:

```
[forward.fluentd]
ca = "/path/to/selfsigned.crt"
cert = "/path/to/selfsigned.crt"
key = "/path/to/selfsigned.key"
url = "https://localhost:8888/test.log"
session-url = "https://localhost:8888/session"
```

## Workaround 2

Realizing that Teleport is basically a fancy CA, I figured it should be doable to use it for this setup. It does work, and is kind of neat.

Generate the fluentd server certificate. Using the `tctl auth sign` command that is usually used to grab a Teleport-signed cert for db access, we can grab one for fluentd.
 
```
$ tctl auth sign --format db --host localhost --overwrite --ttl 8765h -o telserver
Database credentials have been written to telserver.key, telserver.crt, telserver.cas.
...
```

The telserver.key and telserver.crt go in the fluent.conf file for the key and cert. The telserver.cas contains the CA cert for Teleport's host CA. This will go in the ca value in the event forwarder toml.

The identity file itself is already a client cert and key, but it's signed by the teleport user ca, not the host ca. To grab that, run the following command:

``` 
tctl auth export --type user --type tls-user > teluser.cas
```

fluent.conf snippet:

```
    <transport tls>
        client_cert_auth true
        ca_path "/keys/teluser.cas"
        cert_path "/keys/telserver.crt"
        private_key_path "/keys/telserver.key"
        private_key_passphrase "156b63c966bb6ba2ba38fed84dd2f5305d020bbe77bd429f860fc90f93f97deb"
    </transport>
```

teleport-event-handler.toml snippet:
 
```
[forward.fluentd]
ca = "/path/to/telserver.cas"
cert = "/path/to/identity"
key = "/path/to/identity"
url = "https://localhost:8888/test.log"
session-url = "https://localhost:8888/session"
```

**Comment by alexfornuto** [comment] 2023-02-14 20:35
I can confirm this issue, and was able to use workaround 1 to resolve. No luck with workaround 2, likely PEBKAC.

**Comment by alexfornuto** [comment] 2023-03-03 20:20
I have new documentation in the pipeline that assumed the behavior affected by this bug. Should I hold off until this is merged, or rewrite this (and possibly existing docs) to not use this command?

**Comment by travelton** [comment] 2023-03-16 17:01
@alexfornuto I vote for fixing the docs to stop the support volume we are seeing on this issue. Waiting for @xinding33 to comment on the parent issue. Thanks!

**Comment by russjones** [comment] 2023-08-16 17:48
Jeff, Marco:

Let's do this.

1. Propose the planned fix for this issue here. Roman and I will look and tell you if you are on the right track.
2. Once you get a heads up, please submit a PR.

**Comment by programmerq** [comment] 2023-08-16 18:16
The `GenerateMTLSCerts` function generates three certs: a ca, a client cert, and a server cert.

https://github.com/gravitational/teleport-plugins/blob/master/event-handler/mtls_certs.go#L61-L93

My proposed change would be to use a different entity/subject CN for each one.

* The ca can be anything-- "event handler ca"
* The client cert can be anything-- "plugin" would suffice
* The server cert should continue using the value that is passed in ("localhost" by default)

**Comment by r0mant** [comment] 2023-08-16 18:32
`remote error: tls: unknown certificate authority` means that the remote side of the connection (fluentd in this case) can't validate the provided certificate, so I'm not sure what using different subjects is gonna do?

**Comment by programmerq** [comment] 2023-08-16 18:49
The problem is that the CA and the certs it signs have the same Subject and CN.

The OpenSSL library seems to get confused by this and assumes that the client and server cert that have the same Subject and Issuer name are simply self-signed, even when the ca.crt file is configured.

**Comment by jof** [comment] 2023-09-03 17:10
This might also be a duplicate of #696

[I'm hitting a similar issue, but also having verification issues with the Client certificate missing subjectAltNames.](https://github.com/gravitational/teleport-plugins/issues/696#issuecomment-1704339443)

**Closed** 2023-09-06 20:04 UTC
Labels: bug, event-handler, c-bu, c-ntr, c-clm
